name: Substitute Secrets into Json File
description: Substitute GitHub Secrets into a File, matching on a Key name.
author: BankwinG
inputs:
  file:
    required: true
    description: The file to replace.
  output:
    required: false
    description: An optional alternative output file.
  secretsJson:
    required: true
    description: JSON representation of the secrets.
runs:
  using: node16
  main: dist/index.js
branding:
  icon: dollar-sign
  color: gray-dark